import 'dotenv/config';import mongoose from 'mongoose';import bcrypt from 'bcryptjs';import Admin from '../src/models/Admin.js';import Page from '../src/models/Page.js';import MenuItem from '../src/models/MenuItem.js';import ContentCollection from '../src/models/ContentCollection.js';
await mongoose.connect(process.env.MONGODB_URI);
const email=(process.env.ADMIN_EMAIL||'admin@waterhouse.qa').toLowerCase();const password=process.env.ADMIN_PASSWORD||'ChangeMe123!';await Admin.findOneAndUpdate({email},{email,passwordHash:await bcrypt.hash(password,12),role:'admin'},{upsert:true,new:true});
await Page.findOneAndUpdate({slug:'home'},{slug:'home',title:'Water House',hero:{title:'Water, but reimagined.',subtitle:'Choose your water. Add flavour. Add function. A daily hydration ritual made around you.'},seo:{title:'Water House | Modern Hydration Ritual',description:'Water House is a modern water café built around personalized hydration, flavour, function and community.'},published:true},{upsert:true});
const flavours=[['white-peach','White Peach','Soft white peach. Light, juicy and clean.'],['strawberry-salt','Strawberry Salt','Fresh strawberry with a bright saline finish.'],['yuzu-mint','Yuzu Mint','Citrus lift with cool fresh mint.'],['cucumber-lime','Cucumber Lime','Crisp cucumber with fresh lime.'],['green-grape','Green Grape','Clean, juicy green grape.'],['coconut-pandan','Coconut Pandan','Smooth coconut with aromatic pandan.']];
if(await MenuItem.countDocuments()===0) await MenuItem.insertMany(flavours.map(([slug,name,description],i)=>({slug,name,description,category:'Flavour',price:0,sortOrder:i})));
const collections={bases:[['still','Still water'],['sparkling','Sparkling water'],['coconut','Coconut water']],functions:[['electrolytes','Electrolytes','Hydrate deeper.'],['magnesium','Magnesium','Slow down. Reset.'],['creatine','Creatine','Bring the power.'],['collagen','Collagen','Beauty from within.'],['caffeine','Caffeine','Wake your day.'],['l-theanine','L-Theanine','Find your focus.']]};
for(const [type,rows] of Object.entries(collections)){for(let i=0;i<rows.length;i++){const [slug,name,description]=rows[i];await ContentCollection.findOneAndUpdate({type,slug},{type,slug,name,description,sortOrder:i,active:true},{upsert:true,new:true});}}
console.log(`Seed complete. Admin: ${email}`);await mongoose.disconnect();
